language: python
python:
- "2.7"
- "3.4"
os: linux
env:
  - BUILD_TOOL=scons
  - BUILD_TOOL=autotools

matrix:
  include:
  - os: osx
    language: generic
    env: BUILD_TOOL=scons
  - os: osx
    language: generic
    env: BUILD_TOOL=autotools

sudo: required
dist: trusty

addons:
  apt:
    packages:
      - libsdl2-dev
      - scons

before_install:
- source build/.travis/before_install.sh

install:
- source build/.travis/install.sh

before_script:
- pip install pytest pytest-cov
- cd python
- python setup.py develop

script:
- pytest -v
